import { docsSeo, siteSeo, type DocsSeoInput } from "./index";
import type { HeyoDocsConfig } from "../types";

/**
 * React Router-compatible root metadata, including the site-wide WebSite
 * JSON-LD generated by the framework-neutral SEO model.
 */
export function siteSeoMeta(config: HeyoDocsConfig) {
  const seo = siteSeo(config);
  return [
    { title: seo.title },
    { name: "description", content: seo.description },
    { name: "robots", content: "index, follow" },
    { name: "referrer", content: "strict-origin-when-cross-origin" },
    { property: "og:type", content: "website" },
    { property: "og:site_name", content: config.title },
    { property: "og:title", content: seo.title },
    { property: "og:description", content: seo.description },
    { name: "twitter:card", content: "summary" },
    { name: "twitter:title", content: seo.title },
    { name: "twitter:description", content: seo.description },
    ...(seo.canonical
      ? [
          { property: "og:url", content: seo.canonical },
          {
            tagName: "link" as const,
            rel: "canonical",
            href: seo.canonical,
          },
        ]
      : []),
    { "script:ld+json": seo.structuredData },
  ];
}

/**
 * React Router-compatible metadata for documentation, changelog and API pages.
 */
export function docsSeoMeta(input: DocsSeoInput) {
  const seo = docsSeo(input);
  return [
    { title: seo.title },
    { name: "description", content: seo.description },
    { name: "robots", content: "index, follow" },
    { property: "og:type", content: "article" },
    { property: "og:site_name", content: input.config.title },
    { property: "og:title", content: seo.title },
    { property: "og:description", content: seo.description },
    { name: "twitter:card", content: "summary" },
    { name: "twitter:title", content: seo.title },
    { name: "twitter:description", content: seo.description },
    ...(seo.canonical
      ? [
          { property: "og:url", content: seo.canonical },
          {
            tagName: "link" as const,
            rel: "canonical",
            href: seo.canonical,
          },
        ]
      : []),
    { "script:ld+json": seo.structuredData },
  ];
}
